blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ è®¨è®ºåŒº
    url: https://github.com/DyroS3/dy_name_tag/discussions
    about: æœ‰é—®é¢˜æˆ–æƒ³è®¨è®ºï¼Ÿè¯·ä½¿ç”¨è®¨è®ºåŒº
  - name: ðŸ“– æ–‡æ¡£
    url: https://github.com/DyroS3/dy_name_tag#readme
    about: è¯·å…ˆæŸ¥é˜… README æ–‡æ¡£
